FROM node:25-alpine3.21
WORKDIR /app
ARG SERVICE

COPY apps/$SERVICE/dist ./

RUN npm ci --omit=dev && npm cache clean --force || \
    (echo "npm ci failed, falling back to npm install..." && \
     npm install --omit=dev && npm cache clean --force)

CMD ["node", "main.js"]