apiVersion: apps/v1
kind: Deployment
metadata:
  name: aliment-svc-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aliment-svc-mongodb
  template:
    metadata:
      labels:
        app: aliment-svc-mongodb
    spec:
      containers:
        - name: aliment-svc-mongodb
          image: mongo:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGO_INITDB_DATABASE
              value: questnutri
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: root
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: new-taco-json
              mountPath: /docker-entrypoint-initdb.d/new-taco.json
              subPath: new-taco.json
            - name: new-taco-json
              mountPath: /docker-entrypoint-initdb.d/import-taco.sh
              subPath: import-taco.sh

      volumes:
        - name: new-taco-json
          configMap:
            name: new-taco-json
