apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-seed-job
spec:
  template:
    spec:
      containers:
        - name: mongo-seeder
          image: mongo:latest
          command:
            - sh
            - -c
            - mongoimport --uri "mongodb://root:root@aliment-svc-mongodb-service:27017/questnutri?authSource=admin" --collection "taco" --file /seed/new-taco.json --jsonArray
          volumeMounts:
            - name: seed-data
              mountPath: /seed
      restartPolicy: OnFailure
      volumes:
        - name: seed-data
          configMap:
            name: mongo-seed-file
