apiVersion: v1
kind: Service
metadata:
  name: aliment-svc-mongodb-service
spec:
  selector:
    app: aliment-svc-mongodb
  type: LoadBalancer
  ports:
    - port: 27036
      protocol: TCP
      targetPort: 27017
