export const AUTH_SERVICE_PROXY_NAME = 'AUTH_SERVICE';
export const NUTRITIONIST_SERVICE_PROXY_NAME = 'NUTRITIONIST_SERVICE';
export const PATIENT_SERVICE_PROXY_NAME = 'PATIENT_SERVICE';
export const ALIMENT_SERVICE_PROXY_NAME = 'ALIMENT_SERVICE';
export const DIET_SERVICE_PROXY_NAME = 'DIET_SERVICE';
export const RECORD_SERVICE_PROXY_NAME = 'RECORD_SERVICE';