databases:
  - name: auth-postgres
  - name: nutritionist-postgres
  - name: patient-postgres
  - name: diet-postgres
  - name: record-postgres
microservices:
  - name:  auth
    image: auth-svc:latest
    volumeMaps:
      - name: auth-keys-config-map
        keys:
          - private-key.pem
          - public-key.pem
    database: 
      type: postgres
      volumeMaps:
        - name: auth-postgres-config-map
          keys:
            - init.sql
  - name: aliment
    image: aliment-svc:latest
    database: 
      type: mongodb
      volumeMaps:
        - name: new-taco-config-map
          keys:
            - new-taco.json
        - name: home-measures-config-map
          keys:
            - home-measures.json
        - name: import-databases-config-map
          keys:
            - import-databases.sh
  - name: diet
    image: diet-svc:latest
    database:
      type: postgres
  - name: nutritionist
    image: nutritionist-svc:latest
    database:
      type: postgres
  - name: patient
    image: patient-svc:latest
    database:
      type: postgres
  - name: record
    image: record-svc:latest
    database:
      type: postgres
  - name: admin
    image: admin-svc:latest
  - name: gateway
    image: gateway:latest
    port: 8080
    servicePort: 8080
    serviceType: LoadBalancer

rabbitmq: {}