{{- range .Values.databases }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: {{ .name }}
          image: postgres:15-alpine
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_DB
              value: questnutri
            - name: POSTGRES_USER
              value: root
            - name: POSTGRES_PASSWORD
              value: root
          ports:
            - containerPort: 5432
          volumeMounts:
            {{- if eq .name "auth-svc-postgres" }}
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d
            {{- end }}
      volumes:
        {{- if eq .name "auth-svc-postgres" }}
        - name: init-sql
          configMap:
            name: {{ .name }}-init-sql
        {{- end }}
---
{{- end }}