{{- range .Values.databases }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-service
spec:
  selector:
    app: {{ .name }}
  type: LoadBalancer
  ports:
    - port: {{ .port }}
      protocol: TCP
      targetPort: 5432
---
{{- end }}
